database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: ""

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/cadredb

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  validationQueryTimeout: 3s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

logging:
  level: DEBUG
  appenders:
      - type: file
        # The file to which current statements will be logged.
        currentLogFilename: /var/log/cadre/cadre-collector/root.log

        archivedLogFilenamePattern: /var/log/cadre/cadre-collector/root-%i.log

        # The number of archived files to keep.
        archivedFileCount: 10

        # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
        timeZone: UTC

        logFormat: "%-5level [%thread] [%date] %logger: %msg%n%rEx{}%n"

        maxFileSize: 100MB

server:
  applicationConnectors:
  - type: http
    port: 10010
  adminConnectors:
  - type: http
    port: 10011
